// app/src/pages/Signin/Signin.jsx
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import { graphql } from 'react-apollo'

import Button from '../../components/Button'
import Header from '../../components/Header'

import arrow from '../../assets/arrow.svg'

import { LOGIN } from '../graphql/mutations'

class Signin extends Component {
  constructor() {
    super()
    this.state = {
      loading: false,
      username: '',
      password: ''
    }
  }

  inputHandler(e, target) {
    this.setState({
      [target]: e.target.value
    })
  }

  submit = async () => {
    // Отправить форму
    const { username, password } = this.state
    this.setState({ loading: true })
    try {
      const data = await this.props.mutate({ variables: { username, password } })
      // Обработать данные
    } catch(error) {
      // Оповестить пользователя об ошибке
      this.setState({ loading: false })
      throw new Error(error)
    }

  }

  render() {
    const { loading } = this.state
    return (
      <div>
        <div className={'home ' + (loading && 'hide')}>
          <Header/>
          <div className="cards">
              <div className="card rounded">
                  <div className="card-header">Авторизация</div>
                  <div className="card-body">
                      <input type="text" onChange={e => this.inputHandler(e, 'username')} className="line-based" placeholder="Логин"/>
                      <input type="password" onChange={e => this.inputHandler(e, 'password')} className="line-based" placeholder="Пароль"/>
                  </div>
                  <div className="card-footer">
                      <Button clickHandler={this.submit} classNameProp="authorization" text="Войти" />
                  </div>
              </div>
              <Link className="form-link" to="/signup">Нет аккаунта? <img src={arrow}/></Link>
          </div>
      </div>
      {
        loading && <Loading />
      }
      </div>
    )
  }
}

export default graphql(LOGIN)(Signin)

// client/src/views/Signin.vue
<template>
  <div>
    <div class="home" v-show="!loading">
        <Header/>
        <div class="cards">
            <div class="card rounded">
                <div class="card-header">Авторизация</div>
                <div class="card-body">
                    <input type="text" v-model="login" class="line-based" placeholder="Логин">
                    <input type="password" v-model="password" class="line-based" placeholder="Пароль">
                </div>
                <div class="card-footer">
                    <TheButton :clickHandler="submit" className="authorization" text="Войти" />
                </div>
            </div>
        </div>
    </div>
    <Loading v-if="loading"/>
  </div>
</template>

<script>
// @ is an alias to /srс
import Loading from '@/views/Loading.vue'
import Header from '@/components/Header.vue'
import TheButton from '@/components/TheButton.vue'

export default {
    name: 'signin',
    data() {
        return {
            login: '',
            password: '',
            loading: false
        }
    },
    methods: {
        submit() {
            this.loading = true
            setTimeout(() => this.loading = false, 2000)
        },
        fetchData() {

        }
    },
    components: {
        Header,
        TheButton,
        Loading
    }
}
</script>

<style lang="sass">
</style>
