// app/src/pages/Signup/Signup.jsx
import React, { Component } from 'react'
import { Link } from 'react-router-dom'
import { graphql } from 'react-apollo'

import Button from '../../components/Button'
import Header from '../../components/Header'

import arrow from '../../assets/arrow.svg'

import { SIGNUP } from '../graphql/mutations'

class Signup extends Component {
  constructor() {
    super()
    this.state = {
      loading: false,
      firstName: '',
      lastName: '',
      username: '',
      password: ''
    }
  }

  inputHandler(e, target) {
    this.setState({
      [target]: e.target.value
    })
  }

  submit = async () => {
    // Отправить форму

  }

  render() {
    const { loading } = this.state
    return (
      <div>
        <div className={'home ' + (loading && 'hide')}>
          <Header/>
          <div className="cards">
              <div className="card rounded">
                  <div className="card-header">Регистрация</div>
                  <div className="card-body">
                      <input type="text" onChange={e => this.inputHandler(e, 'firstName')} className="line-based" placeholder="Имя"/>
                      <input type="text" onChange={e => this.inputHandler(e, 'lastName')} className="line-based" placeholder="Фамилия"/>
                  </div>
                  <div className="card-footer">
                      <Button clickHandler={this.submit} classNameProp="authorization" text="Войти" />
                  </div>
              </div>
              <Link className="form-link" to="/signin">Есть аккаунт? <img src={arrow}/></Link>
          </div>
      </div>
      {
        loading && <Loading />
      }
      </div>
    )
  }
}

export default graphql(SIGNUP)(Signup)

// client/src/views/Signup.vue
<template>
  <div>
    <div class="home" v-show="!loading">
      <Header/>
      <div class="cards">
        <div class="card rounded">
          <div class="card-header">Регистрация</div>
          <div class="card-body">
            <input type="text" v-model="firstName" class="line-based" placeholder="Имя">
            <input type="text" v-model="lastName" class="line-based" placeholder="Фамилия">
          </div>
          <div class="card-footer">
            <TheButton :clickHandler="submit" className="authorization" text="Дальше" />
          </div>
        </div>
        <router-link class="form-link" to="/signin">Есть аккаунт? <img src="@/assets/arrow.svg"></router-link>
      </div>
    </div>
    <Loading v-if="loading" />
  </div>
</template>

<script>
  // @ is an alias to /srс
  import Loading from '@/views/Loading.vue'
  import Header from '@/components/Header.vue'
  import TheButton from '@/components/TheButton.vue'

  export default {
    name: 'signup',
    data() {
      return {
        firstName: '',
        lastName: '',
        loading: false
      }
    },
    methods: {
      submit() {
        this.loading = true
        setTimeout(() => this.loading = false, 2000)
      },
      fetchData() {

      }
    },
    components: {
      Header,
      TheButton,
      Loading
    }
  }
</script>

<style lang="sass" scoped>
</style>
